services:
  bridge-sdp:
    build: .
    container_name: bridge-sdp
    hostname: bridge-sdp
    restart: unless-stopped
    volumes:
      - /opt/tendril/tendril:/opt/tendril/tendril:ro
      - ./config/tendril.json:/opt/tendril/tendril.json:ro
    networks:
      - tendril

networks:
  tendril:
    external: true
